steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA",
        "-f",
        "docker/Dockerfile",
        ".",
      ]

  # Push the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA",
      ]

  # Deploy to GKE using kubectl
  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - CLOUDSDK_COMPUTE_REGION=us-central1-a
      - CLOUDSDK_CONTAINER_CLUSTER=originhub-prod
    args:
      [
        "set",
        "image",
        "deployment/backend",
        "backend=us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA",
      ]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
