"""Create ideas table

Revision ID: 72f39089bf0c
Revises: 5ca545761e52
Create Date: 2025-01-27 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "72f39089bf0c"
down_revision: Union[str, None] = "5ca545761e52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop old ideas table if it exists
    op.execute("DROP TABLE IF EXISTS ideas CASCADE")

    # Create new ideas table
    op.create_table(
        "ideas",
        sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("solution", sa.Text(), nullable=False),
        sa.Column("marketSize", sa.String(length=255), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("upvotes", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ideas_id"), "ideas", ["id"], unique=False)
    op.create_index(op.f("ix_ideas_user_id"), "ideas", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ideas_user_id"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_id"), table_name="ideas")
    op.drop_table("ideas")
    # ### end Alembic commands ###
