"""add_parent_comment_id_to_comments

Revision ID: ebfb45bc397d
Revises: 4091051982ce
Create Date: 2025-11-21 16:45:01.205704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfb45bc397d'
down_revision: Union[str, None] = '4091051982ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_comment_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_comments_parent_comment_id'), 'comments', ['parent_comment_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_parent_comment_id'), table_name='comments')
    op.drop_column('comments', 'parent_comment_id')
    # ### end Alembic commands ###

